manifest:
  remotes:
    - name: darknao
      url-base: https://github.com/darknao
  projects:
      - name: zmk
      remote: darknao
      revision: tree/darknao/rgb-dts
      import: app/west.yml
  self:
    path: config
