manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/darknao/zmk/tree/darknao/rgb-dts
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
